name: Docker
on: 
  push:
  pull_request:
jobs:
  docker-container:
    runs_on: ubuntu-latest
    container:
      image: ubuntu:18.04
    steps:
      name: print os release
      run: echo /etc/os_release


  


      