name: Docker
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  docker-container:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:18.04
    steps:
      - name: print os release
        run: cat /etc/os-release
      - name: print node version
        continue-on-error: true
        run: node -v
      - name: use another docker container and check
        uses: docker://node:18-alpine
        with:
          entrypoint: "/usr/local/bin/node"
          args: -v
#      - name: print node version
#        run: node -v
