name: Docker
on: 
  push:
  pull_request:
jobs:
  docker-container:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04
    steps:
      - name: print os release
        run: cat /etc/os-release


  


      