name: Docker-first
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  docker-container:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:18.04
      #credentials:
      #  username:
      #  password:
      ports:
        - 8080
      volumes:
        - .:/path-to-container
    steps:
      - name: print os release
        run: cat /etc/os-release
