name: Shell Commands 

on:  
  pull_request:
  push:
    branches:
      - "main"
  repository_dispatch:
    types: "build"


jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo username
        run: echo ${{ github.event.client_payload.user }}
        timeout-minutes: 0
      - name: multiline script 
        run: |
           node -v 
           npm -v
      - name: python Command 
        run: |
          import platform 
          print
          (platform.processor())
        shell: python
      - name: git clone
        uses: actions/checkout@v1
      - name: run first shell script
        run: |
          touch second.sh
          chmod 777 second.sh
          ./first.sh>second.sh
          cat second.sh
      - name: pushing second.sh in git
        run: |
          git checkout main
          git config --global user.name 'Ravi Gulati'
          git config --global user.email 'ravigulati416@gmail.com'
          git add second.sh
          git commit -m "adding second file from workflow"
          git remote add origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ GITHUB_REPOSITORY }}.git
          git push origin main
  run-windwos-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory PowerShell
        run: Get-Location 
      - name: Directory Bash 
        run: pwd 
        shell: bash 