name: Shell Commands 

on:  
  pull_request:
  repository_dispatch:
    types: "build"


jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo username
        run: echo ${{ github.event.client_payload.user }}
        timeout-minutes: 0
      - name: multiline script 
        run: |
           node -v 
           npm -v
      - name: python Command 
        run: |
          import platform 
          print
          (platform.processor())
        shell: python
  run-windwos-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory PowerShell
        run: Get-Location 
      - name: Directory Bash 
        run: pwd 
        shell: bash 