name: First Action for cross platform testing

on:
  pull_request:
  push:
    #Push to second_feature branch mentioned below will not work if this branch does not have copy of this workflow
    branches: [ "main", "second_feature" ]
  workflow_dispatch:
  schedule:
    - cron: "0 1 1 * *"

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo username
        run: echo $GITHUB_ACTOR
        timeout-minutes: 0
      - name: multiline script
        run: |
          ls -l
          node -v 
          npm -v 
      - name: python Command
        run: |
          import platform 
          print(platform.processor())
        shell: python
      - name: git clone
        uses: actions/checkout@v2
        #Right now checkoutand git push is running using built-in github token, uncomment below PAT to run workflow on git push.
        #caution: UNcommenting below with tag will make it enter into infinite loop for running workflow.  
        #with:
        #  token: ${{ secrets.PERSONAL_ACTION_TOKEN }}
      - run: |
          git config --global user.name 'Ravi Gulati'
          git config --global user.email 'ravigulati416@gmail.com'
          ./first.sh>second.sh
          ls -a
          cat second.sh
          git add second.sh
          git commit -m "adding second file from workflow"
          git push
      #      - name: push random script in github repo
      #        run: |
                  #git checkout main
                  #git config --global credential.helper cache
                  #remove below comment and stuck in infinite loop, disable worklow to come out of that loop 
                  ##git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.PERSONAL_ACTION_TOKEN }}@github.com/Ravigulati416/github_action_udemy.git
                  #git config --global user.name 'Ravi Gulati'
                  #git config --global user.email 'ravigulati416@gmail.com'
                  #./first.sh>second.sh
                  #ls -a
                  #cat second.sh
                  #git add second.sh
                  #git commit -m "adding second file from workflow"
                  #git push

  run-windwos-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
