name: git checkout and push

on:
  pull_request:
  push:
    branches:
      - "main"
  workflow_dispatch:
  schedule:
    - cron: "0 1 1 * *"

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo username
        run: echo ${{ github.event.client_payload.user }}
        timeout-minutes: 0
      - name: multiline script
        run: |
          ls -l
          node -v 
          npm -v
      - name: python Command
        run: |
          import platform 
          print(platform.processor())
        shell: python
      - name: git clone
        uses: actions/checkout@v1
      #      - name: push random script in github repo
      #        run: |
      #          git init
      #          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/Ravigulati416/github_action_udemy.git"
      #          git config --global user.name 'Ravi Gulati'
      #          git config --global user.email 'ravigulati416@gmail.com'
      #          git fetch
      #          git checkout main
      #          git branch set-upstream-to=origin/main
      #          git pull
      #          ls -a
      #          ps>second.sh
      #          git add second.sh
      #          git commit -m "adding second file from workflow"
      #          git push origin main
      - name: pushing second.sh in git
        run: |
          git checkout main
          git config --global credential.helper cache
          git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/Ravigulati416/github_action_udemy.git
          git config --global user.name 'Ravi Gulati'
          git config --global user.email 'ravigulati416@gmail.com'
          ./first.sh>second.sh
          ls -a
          cat second.sh
          git add second.sh
          git commit -m "adding second file from workflow"
          git push origin main
  run-windwos-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
