name: Shell Commands

on:
  push:
    branches:
      - "main"

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo username
        run: echo ${{ github.event.client_payload.user }}
        timeout-minutes: 0
      - name: multiline script
        run: |
          node -v 
          npm -v